need to figure out how to save an object that might already exist
mongoengine.errors.NotUniqueError: Tried to save duplicate unique keys
(E11000 duplicate key error index: uclaapi_test.course.$instructor_1
dup key: { : "IVANOVA, O." })